config/routes.rb
Rise::Application.routes.draw do

  root 'welcome#index'

  resources :decisions, only: [:index, :update]

  resources :questions, only: :show

  resource :report, only: :show

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
  serialize :meta

  scope :upsert, ->(attrs) {
    question = self.first_or_initialize
    attrs.each do |attr, value|
      question.send("#{attr}=", value)
    end
    question.save!
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter do
    headers['Last-Modified'] = Time.now.httpdate
  end
end

app/controllers/decisions_controller.rb
class DecisionsController < ApplicationController
  PARTIALS = {
    'MultipleChoiceQuestion' => 'questions/multiple_choice',
    'NumericQuestion' => 'questions/numeric',
  }

  def index
    # if user is in the middle of answering, continue
    # else
    redirect_to question_path("q1")
  end

  def update
    question_id = answer_params[:id]
    response = answer_params[:value]

    answer = Answer.where(
      user_id: session[:user_id],
      question_id: question_id
    ).first_or_initialize

    answer.response = response
    answer.save

    status, question_name = DecisionTree.next_question(answer)

    case status
    when :ok
      redirect_to question_path(question_name)
    when :done
      redirect_to report_path
    end

  end

  private
  def answer_params
    params.permit(:id, :value)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  PARTIALS = {
    'MultipleChoiceQuestion' => 'questions/multiple_choice',
    'NumericQuestion' => 'questions/numeric',
  }

  COMPLETION = {
    "q1" => 0,
    "q2" => 5,
    "q3" => 10,
    "q4" => 16,
    "q5" => 22,
    "q5a" => 30,
    "q5b" => 35,
    "q5c" => 38,
    "q5d" => 45,
    "q6" => 50,
    "q7" => 55,
    "q8" => 62,
    "q10" => 68,
    "q12" => 74,
    "q13" =>79,
    "q14" => 87,
    "q15" => 95,
  }

  def show
    @question = Question.find_by_name params[:id]
    @partial = PARTIALS[@question.kind]
    @percent_done = COMPLETION[@question.name]
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def show
    @cal_works = Eligible::CalWorks.new(session[:user_id]).eligible?
    @cal_fresh = Eligible::CalFresh.new(session[:user_id]).eligible?
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  WORDS = %w{action active admire agree amazing angelic approve awesome beaming believe bliss bounty brave bravo bubbly calm certain champ cheery choice classic clean commend cool cute delight divine earnest easy elegant ethical fair famous fine fitting free fresh fun funny genius genuine giving glowing good great green grin growing happy healing healthy hearty honest honored hug idea ideal imagine instant jovial joy keen kind knowing laugh light learned lively lovely lucid lucky merit moving natural nice novel now okay one open perfect poised popular pretty proud quality quick quiet ready refined rejoice reward right robust safe secure seemly simple skilled smile soulful special success sunny super superb tops unreal up upbeat upright valued vibrant victory vital wealthy welcome well whole willing worthy wow yes yummy zeal zealous}
  
  def index
    session[:user_id] = generate_user_id
  end

  def my_code
  end

  private
  def generate_user_id
    WORDS.sample(3).join(' ')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/decisions/index.html.erb
<h1>Mission Rise</h1>

<h2>Question</h2>

<div>
  <%= @question.prompt %>
</div>


<div>
  <%= form_tag decision_path(id:@question.id), method: :put do %>
      <%= render @partial, meta: @question.meta %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mission Rise</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <span class="glyphicon glyphicon-fire" style="color:white"></span>
        Mission Rise
      </a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Find Benefits", decisions_path %></li>
        <li><a href="#">Resources</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="main">
  <%= yield %>
</div>

</body>
</html>

app/views/questions/_multiple_choice.html.erb
<% meta.each_with_index do |option, i| %>
    <%= submit_tag option, name: :value, class: "btn btn-primary #{i == 0 ? "yes" : "no"}" %>
<% end %>

app/views/questions/_numeric.html.erb
<div class="numeric">
  <%= text_field_tag :value, nil, size: 20 %>
</div>
<%= submit_tag "Next", class: "btn btn-primary next" %>

app/views/questions/show.html.erb
<div class="jumbotron text-xs-center">
  <div class="progress">
  <div class="progress-bar" style="width:<%= @percent_done %>%">
    <span><%= @percent_done %>% Complete</span>
  </div>
</div>
  <div class="prompt"><%= @question.prompt %></div>
  <div class="options">
    <%= form_tag decision_path(id:@question.id), method: :put do %>
        <%= render @partial, meta: @question.meta %>
    <% end %>
  </div>
</div>

app/views/reports/show.html.erb
<div class="jumbotron text-xs-center">
  <%= image_tag 'congrats.png', style: "width: 100%" %>
  <hr>
  <%= image_tag 'best.png', style: "width: 100%; max-width: 600px;"  %>
  <hr>
  <%= image_tag 'next.png', style: "width: 100%; max-width: 600px"  %>
</div>

app/views/welcome/index.html.erb
<div class="welcome center">
  <div class="hero-container">
    <div class="hero">
      <div class="welcome-title">Easier for You. Better for your family.</div>
      <p><%= link_to "Find My Benefits", decisions_path, class: 'btn btn-primary btn-lg btn-welcome' %></p>
    </div>
  </div>
</div>